In [119]:
print("----------------------------------------------------NUMPY-----------------------------------------------------")

----------------------------------------------------NUMPY-----------------------------------------------------


In [120]:
import numpy as np
a=np.array([32,43,65,67])
# b=np.array([32,43,65,67])
b=5
print(a*b)

[160 215 325 335]


In [121]:
import numpy as np
a=np.array([[32,43,65,67],[56,65,56,67,89]])
print(a)

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [ ]:
import numpy as np
ar=np.array([53,65])
print(ar)
print(type(ar))

[53 65]
<class 'numpy.ndarray'>


In [ ]:
#slicing
import numpy as np
ar=np.array([53,65,45,56,67,87,87])
print(ar[:5])

[53 65 45 56 67]


In [ ]:
print("-----------------------------------inspecting an array--------------------------------------------")

-----------------------------------inspecting an array--------------------------------------------


In [ ]:
import numpy as np
ar=np.array([[53,65,45,56,87],[86,35,45,56,87]])
print(ar[0:2,0:2])
print(ar[0,1:4])
print()
print(np.shape(ar))
print(ar.shape)
print()
print(np.size(ar))
print(ar.size)
print()
print(np.ndim(ar))
print(ar.ndim)
print()
print(ar.dtype)
print()
print(ar.astype(str))


[[53 65]
 [86 35]]
[65 45 56]

(2, 5)
(2, 5)

10
10

2
2

int32

[['53' '65' '45' '56' '87']
 ['86' '35' '45' '56' '87']]


In [ ]:
print("--------------------------------Mathematical operations and functions on array--------------------------------")

--------------------------------Mathematical operations and functions on array--------------------------------


In [ ]:
#--------------------------------------------------ADD---------------------------------------------------------------
import numpy as np
arr1=np.array([54,5,65,65,7,67,67,78])
arr2=np.array([54,5,65,65,7,67,67,78])
print(np.add(arr1,arr2))

[108  10 130 130  14 134 134 156]


In [ ]:
#-----------------------------------------------------SUBTRACT-------------------------------------------------------
import numpy as np
arr1=np.array([54,5,65,65,7,67,67,78])
arr2=np.array([54,5,65,65,7,67,67,78])
print(np.subtract(arr1,arr2))

[0 0 0 0 0 0 0 0]


In [ ]:
import numpy as np
arr1=np.array([54,5,65,65,7,67,67,78])
arr2=np.array([2])
print(np.power(arr1,arr2))

[2916   25 4225 4225   49 4489 4489 6084]


In [ ]:
import numpy as np
arr1=np.array([54,5,65,65,7,67,67,78])
print(np.sqrt(arr1))

[7.34846923 2.23606798 8.06225775 8.06225775 2.64575131 8.18535277
 8.18535277 8.83176087]


In [ ]:
print("----------------------------combining and splitting Arrays------------------------------------------------")

----------------------------combining and splitting Arrays------------------------------------------------


In [ ]:
#concatenate
import numpy as np
arr1=np.array([54,5,65,65,7,67,67,78])
arr2=np.array([54,5,65,65,7,67,67,78])
print(np.concatenate(([arr1,arr2])))

[54  5 65 65  7 67 67 78 54  5 65 65  7 67 67 78]


In [ ]:
import numpy as np
arr1=np.array([[54,5,65,65],[7,67,67,78]])
arr2=np.array([[24,5,65,65],[7,67,67,78]])
print(np.concatenate([arr1,arr2],axis=1))
print(np.hstack([arr1,arr2]))

[[54  5 65 65 24  5 65 65]
 [ 7 67 67 78  7 67 67 78]]
[[54  5 65 65 24  5 65 65]
 [ 7 67 67 78  7 67 67 78]]


In [126]:
import numpy as np
arr1=np.array([[54,5,65,65],[7,67,67,78]])
arr2=np.array([[24,5,65,65],[7,67,67,78]])
print(np.concatenate([arr1,arr2],axis=0))
print(np.vstack([arr1,arr2]))

[[54  5 65 65]
 [ 7 67 67 78]
 [24  5 65 65]
 [ 7 67 67 78]]
[[54  5 65 65]
 [ 7 67 67 78]
 [24  5 65 65]
 [ 7 67 67 78]]


In [125]:
#split
import numpy as np
arr1=np.array([54,5,65,65,7,67,67,78,56])
brr=np.array_split(arr1,3)
print(brr)

[array([54,  5, 65]), array([65,  7, 67]), array([67, 78, 56])]


In [122]:
import numpy as np
arr1=np.array([54,5,65,65,7,67,67,78])
print(np.append(arr1,[90]))

[54  5 65 65  7 67 67 78 90]


In [123]:
import numpy as np
arr1=np.array([54,5,65,65,7,67,67,78])
print(np.insert(arr1,1,30))

[54 30  5 65 65  7 67 67 78]


In [124]:
import numpy as np
arr1=np.array([54,5,65,65,7,67,67,78])
print(np.delete(arr1,0))

[ 5 65 65  7 67 67 78]


In [130]:
import numpy as np
arr1=np.array([[54,5,65,65],[7,67,67,78]])
print(np.delete(arr1,1,axis=0))

[[54  5 65 65]]


In [132]:
print("----------------------------------------------Search,sort and filter-----------------------------------------")

----------------------------------------------Search,sort and filter-----------------------------------------


In [136]:
import numpy as np
arr1=np.array([54,5,65,65,7,67,67,78])
arr2=np.array([[24,5,95,65],[7,67,67,78]])
print(np.sort(arr1))
print(np.sort(arr2))

[ 5  7 54 65 65 67 67 78]
[[ 5 24 65 95]
 [ 7 67 67 78]]


In [141]:
import numpy as np
arr1=np.array([54,5,65,65])
s=np.where(arr1==5)
print(s)

(array([1], dtype=int64),)


In [146]:
#filter
import numpy as np
arr1=np.array([54,5,65,65])
fa=[True,False,True,False]
new=arr1[fa]
print(new)

[54 65]


In [149]:
import numpy as np
arr1=np.array([54,5,65,95])
fa=arr1>60
new=arr1[fa]
print(new)

[65 95]


In [ ]:
print("----------------------------------------------Aggergation function-----------------------------------------")

In [155]:
import numpy as np
b=np.array([23,54,67,89])
print(np.sum(b))
print(np.min(b))
print(np.max(b))
print(np.size(b))
print(np.mean(b))
print(np.cumsum(b))
print(np.cumprod(b))

233
23
89
4
58.25
[ 23  77 144 233]
[     23    1242   83214 7406046]


In [163]:
import numpy as np
arr1=np.array([54,5,65,65,7,67,67,78])
arr2=np.array([54,5,65,65,7,67,67,78])
c=np.cumprod([arr1,arr2],axis=0)
print(c[1].sum())

26502


In [166]:
print("---------------------------------------------statical function------------------------------------------------")

---------------------------------------------statical function------------------------------------------------


In [176]:
import numpy as np
import statistics as ss
arr4=np.array([45,34,67,34,65,98,76])
print(np.mean(arr4))
print(np.median(arr4))
print(ss.mode(arr4))
print(np.std(arr4))

59.857142857142854
65.0
34
21.879073964659025


In [182]:
import numpy as np
arr1=([12,23,34,56,67,78,89])
arr2=([98,87,76,65,54,43,32])
print(np.corrcoef([arr1,arr2]))

[[ 1.         -0.99484975]
 [-0.99484975  1.        ]]


In [4]:
#How to create an empty and a full NumPy array?
import numpy as np
ar1=np.array([])
ar=np.array([23,45,67,89])
print(ar)
print(ar1)

[23 45 67 89]
[]


In [5]:
#Create a Numpy array filled with all zeros
import numpy as np
arr=np.array([0,0,0,0])
print(arr)

[0 0 0 0]
